//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ingest_Assistant.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\10.2.68.19\\Work\\Ingest_2_16")]
        public string Work_Path {
            get {
                return ((string)(this["Work_Path"]));
            }
            set {
                this["Work_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\10.2.68.19\\Inbox\\Stock")]
        public string Stock_Path {
            get {
                return ((string)(this["Stock_Path"]));
            }
            set {
                this["Stock_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\10.2.68.19\\Inbox\\_MASTER_Prep")]
        public string Master_Path {
            get {
                return ((string)(this["Master_Path"]));
            }
            set {
                this["Master_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\10.2.68.19\\Work\\Ingest_2_16\\WorkARCHIVE")]
        public string Archive_Path {
            get {
                return ((string)(this["Archive_Path"]));
            }
            set {
                this["Archive_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\10.2.68.19\\Work\\Ingest_2_16\\WorkARCHIVE\\Shablon")]
        public string Shablon_Path {
            get {
                return ((string)(this["Shablon_Path"]));
            }
            set {
                this["Shablon_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\10.2.68.19\\Work\\Ingest_2_16\\WorkARCHIVE\\Shablon\\Ingest Assistant.sdf")]
        public string MetaBase_Way {
            get {
                return ((string)(this["MetaBase_Way"]));
            }
            set {
                this["MetaBase_Way"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color Browser_Is_In_Archive_Dir {
            get {
                return ((global::System.Drawing.Color)(this["Browser_Is_In_Archive_Dir"]));
            }
            set {
                this["Browser_Is_In_Archive_Dir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color Browser_Isnt_In_Work_Dir {
            get {
                return ((global::System.Drawing.Color)(this["Browser_Isnt_In_Work_Dir"]));
            }
            set {
                this["Browser_Isnt_In_Work_Dir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double Work_Max_Value {
            get {
                return ((double)(this["Work_Max_Value"]));
            }
            set {
                this["Work_Max_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double Arch_Max_Value {
            get {
                return ((double)(this["Arch_Max_Value"]));
            }
            set {
                this["Arch_Max_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Turquoise")]
        public global::System.Drawing.Color Browser_Is_In_Archive_Dir_NOT_TODAY {
            get {
                return ((global::System.Drawing.Color)(this["Browser_Is_In_Archive_Dir_NOT_TODAY"]));
            }
            set {
                this["Browser_Is_In_Archive_Dir_NOT_TODAY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Turquoise")]
        public global::System.Drawing.Color Browser_Isnt_In_Work_Dir_NOT_TODAY {
            get {
                return ((global::System.Drawing.Color)(this["Browser_Isnt_In_Work_Dir_NOT_TODAY"]));
            }
            set {
                this["Browser_Isnt_In_Work_Dir_NOT_TODAY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\\\Ingest Assistant Temp Files")]
        public string Temp_Files_Directory {
            get {
                return ((string)(this["Temp_Files_Directory"]));
            }
            set {
                this["Temp_Files_Directory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\10.2.68.19\\Work\\Ingest_2_16\\WorkARCHIVE\\Base_Archive")]
        public string Base_Archive {
            get {
                return ((string)(this["Base_Archive"]));
            }
            set {
                this["Base_Archive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\10.2.68.19\\Work\\Complete")]
        public string Complete_Path {
            get {
                return ((string)(this["Complete_Path"]));
            }
            set {
                this["Complete_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public string Day_Work_Time {
            get {
                return ((string)(this["Day_Work_Time"]));
            }
            set {
                this["Day_Work_Time"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1|2|3")]
        public string Additional_Work_Types {
            get {
                return ((string)(this["Additional_Work_Types"]));
            }
            set {
                this["Additional_Work_Types"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\\\Ingest Assistant Temp Files\\LogDataBase.sdf")]
        public string Log_Base_Path {
            get {
                return ((string)(this["Log_Base_Path"]));
            }
            set {
                this["Log_Base_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_Profile {
            get {
                return ((string)(this["Setting_Profile"]));
            }
            set {
                this["Setting_Profile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\10.2.68.19\\Work\\Ingest_2_16\\Ingest Assistant\\IASettingsBase.sdf")]
        public string Setting_Base_Path {
            get {
                return ((string)(this["Setting_Base_Path"]));
            }
            set {
                this["Setting_Base_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Direct_Show_Adress {
            get {
                return ((string)(this["Direct_Show_Adress"]));
            }
            set {
                this["Direct_Show_Adress"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int Max_Elements_For_DGV {
            get {
                return ((int)(this["Max_Elements_For_DGV"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color Group1Color {
            get {
                return ((global::System.Drawing.Color)(this["Group1Color"]));
            }
            set {
                this["Group1Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color Group2Color {
            get {
                return ((global::System.Drawing.Color)(this["Group2Color"]));
            }
            set {
                this["Group2Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color Group3Color {
            get {
                return ((global::System.Drawing.Color)(this["Group3Color"]));
            }
            set {
                this["Group3Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color Group4Color {
            get {
                return ((global::System.Drawing.Color)(this["Group4Color"]));
            }
            set {
                this["Group4Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color Group5Color {
            get {
                return ((global::System.Drawing.Color)(this["Group5Color"]));
            }
            set {
                this["Group5Color"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("server=10.2.102.108;database=ingestassistantsettingsbase;user id=IA;password=QAz1" +
            "23456;")]
        public string Main_Settings_Base_Path {
            get {
                return ((string)(this["Main_Settings_Base_Path"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Alow_Logging {
            get {
                return ((bool)(this["Alow_Logging"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1|2|3|4|5|6")]
        public string Consolidate_Directories {
            get {
                return ((string)(this["Consolidate_Directories"]));
            }
            set {
                this["Consolidate_Directories"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Profile_ID {
            get {
                return ((int)(this["Profile_ID"]));
            }
            set {
                this["Profile_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Reservations {
            get {
                return ((string)(this["Reservations"]));
            }
            set {
                this["Reservations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MetaDate {
            get {
                return ((string)(this["MetaDate"]));
            }
            set {
                this["MetaDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MetaData {
            get {
                return ((string)(this["MetaData"]));
            }
            set {
                this["MetaData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Other_Work_File_Types {
            get {
                return ((string)(this["Other_Work_File_Types"]));
            }
            set {
                this["Other_Work_File_Types"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int User_ID {
            get {
                return ((int)(this["User_ID"]));
            }
            set {
                this["User_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Base_Show_Setting {
            get {
                return ((string)(this["Base_Show_Setting"]));
            }
            set {
                this["Base_Show_Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string XML_Editor_Path {
            get {
                return ((string)(this["XML_Editor_Path"]));
            }
            set {
                this["XML_Editor_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AdminMode {
            get {
                return ((bool)(this["AdminMode"]));
            }
            set {
                this["AdminMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Base_Show_Setting_Set {
            get {
                return ((string)(this["Base_Show_Setting_Set"]));
            }
            set {
                this["Base_Show_Setting_Set"] = value;
            }
        }
    }
}
